//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCapp01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Log2
    {
        public int Id { get; set; }
        public string Esemeny { get; set; }
        public string Eredmeny { get; set; }
        public System.DateTime Ido { get; set; }
    }
}
