//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCapp01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UserDbEntities : DbContext
    {
        public UserDbEntities()
            : base("name=UserDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_User2> tbl_User2 { get; set; }
        public virtual DbSet<tbl_User_Log2> tbl_User_Log2 { get; set; }
    
        public virtual int Adatmigracio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Adatmigracio");
        }
    
        public virtual ObjectResult<Adatmigracio_test_Result> Adatmigracio_test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Adatmigracio_test_Result>("Adatmigracio_test");
        }
    
        public virtual int Logolas(string esemeny, string eredmeny)
        {
            var esemenyParameter = esemeny != null ?
                new ObjectParameter("Esemeny", esemeny) :
                new ObjectParameter("Esemeny", typeof(string));
    
            var eredmenyParameter = eredmeny != null ?
                new ObjectParameter("Eredmeny", eredmeny) :
                new ObjectParameter("Eredmeny", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Logolas", esemenyParameter, eredmenyParameter);
        }
    
        public virtual int Logolas2(string esemeny, string eredmeny, Nullable<System.DateTime> ido)
        {
            var esemenyParameter = esemeny != null ?
                new ObjectParameter("Esemeny", esemeny) :
                new ObjectParameter("Esemeny", typeof(string));
    
            var eredmenyParameter = eredmeny != null ?
                new ObjectParameter("Eredmeny", eredmeny) :
                new ObjectParameter("Eredmeny", typeof(string));
    
            var idoParameter = ido.HasValue ?
                new ObjectParameter("Ido", ido) :
                new ObjectParameter("Ido", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Logolas2", esemenyParameter, eredmenyParameter, idoParameter);
        }
    
        public virtual int Urites()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Urites");
        }
    }
}
